### ISSUE TITLE
Demo referenced in Readme - where is the demo?

### ISSUE THREAD

**Issue by dexterfitch** [learn-co-curriculum/react-hooks-state-and-events-lab#1]
## Link to Canvas

https://learning.flatironschool.com/courses/2674/assignments/123703?module_item_id=255315

## What should be changed?

The readme references a demo students should follow, but doesn't indicate what or where the demo is.

**Comment by ihollander** [comment]
@dexterfitch thanks for flagging! Just fixed: https://github.com/learn-co-curriculum/react-hooks-state-and-events-lab/commit/3c03f12e3749e3d250ae205b4794b9c254c7e567
